[package]
name = "rust-v2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.3"

crossbeam-channel = "0.5"

image = "0.23"

cgmath = { version = "0.18", features = ["serde"] }