[package]
name = "rust-v2"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.131", features = ["derive", "rc"] }
serde-big-array = "0.3.2"
typetag = "0.1.8"
ron = "0.7.0"
bincode = "1.3.3"
lz4_flex = "0.9.2"

fastrand = "1.5.0"
bitflags = "1.3.2"
image = "0.23.14"
cgmath = { version = "0.18.0", features = ["serde"] }

crossbeam-channel = "0.5.1"
parking_lot = { version = "0.11.2", features = ["serde"] }
num_cpus = "1.13.0"
signal-hook = "0.3.12"

show-image = { version = "0.10.1", features = ["image", "save"], optional = true }

log = "0.4.14"
env_logger = "0.9.0"

itertools = "0.10.3"
poloto = "3.11.0"

[features]
default = ["spectral"]
spectral = []
srgb = []
xyz = []
f64 = []
watertight-mesh = ["f64"]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
incremental = true

[[bin]]
name = "srgb-vs-spectrum"
required-features =  ["show-image"]
